config/routes.rb
Rails.application.routes.draw do
  

  resources :technologies

  root 'technologies#index'

end

app/models/technology.rb
class Technology < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
	validates :description, presence: true, length: { minimum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  
  #GET /technologies
  def index
  	@technologies = Technology.all
  end

  #GET /technologies/:id
  def show
  	@technology = Technology.find(params[:id])
  end

  #GET /technologies/new
  def new
  	@technology = Technology.new
  end

  #POST /technologies
  def create
  	@technology = Technology.new(technology_params)
  	if @technology.save
  		redirect_to technologies_path
  	else
  		render :new
  	end
  end

  #DELETE /technologies/:id
  def destroy
  	@technology = Technology.find(params[:id])
  	@technology.destroy
  	redirect_to technologies_path
  end

  def edit 
    @technology = Technology.find(params[:id])
  end

  #PUT technologies/:id
  def update
    @technology = Technology.find(params[:id])
    if @technology.update(technology_params)
      redirect_to technologies_path
    else
      render :edit
    end
  end

  private

  def technology_params
    params.require(:technology).permit(:name,:description,:version,:link)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 1.0
        </div>
        <strong>Copyright &copy; 2015 <a href="#">Luis Gomez</a>.</strong> All rights reserved.
      </footer>

app/views/layouts/_nav_left.html.erb
<!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel">
            <div class="pull-left image">
              <%= image_tag "user2-160x160.jpg", class: "img-circle" %>
            </div>
            <div class="pull-left info">
              <p>Luis Gómez</p>

              <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
          </div>
          <!-- search form -->
          <!--<form action="#" method="get" class="sidebar-form">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Search..."/>
              <span class="input-group-btn">
                <button type='submit' name='seach' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </form>-->
          <!-- /.search form -->
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu">
            <li class="header"></li>
            <li><%= link_to technologies_path(@technology) do %>
              <i class="fa fa-github"></i> Technologies
            <% end %></li>
          </ul>
        </section>
        <!-- /.sidebar -->
      </aside>

app/views/layouts/_nav_top.html.erb
<header class="main-header">
        <a href="contract.php" class="logo"><b>Project Name</b></a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">              
              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= image_tag "user2-160x160.jpg", class: "user-image" %>
                  <span class="hidden-xs">Luis Gómez</span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                    <%= image_tag "user2-160x160.jpg", class: "img-circle" %>
                    <p>
                      Luis Gómez - Web Developer
                      <small>Member since Nov. 2012</small>
                    </p>
                  </li>
                  <!-- Menu Body -->
                  <li class="user-body">
                    <div class="col-xs-6 text-center">
                      <!--<a href="#" id="english">ssdd</a>-->
                    </div>
                    <div class="col-xs-6 text-center">
                      <!--<a href="#" id="spanish">dsd</a>-->
                    </div>
                  </li>
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="profile.php" class="btn btn-default btn-flat">Profile</a>
                    </div>
                    <div class="pull-right">
                      <a href="logout.php" class="btn btn-default btn-flat">Sign out</a>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<title>Blog</title>
  	
    <%= stylesheet_link_tag "bootstrap.min" %>
  	<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" %>
  	<%= stylesheet_link_tag "http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" %>
    <%= stylesheet_link_tag "plugins/dataTables.bootstrap.css" %>
    <%= stylesheet_link_tag "AdminLTE.min.css" %>
    <%= stylesheet_link_tag "all-skins.min.css" %>
    <%= stylesheet_link_tag "http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" %>
    <%= javascript_include_tag 'jquery' %>
    <%= javascript_include_tag 'jquery_ujs' %>
  </head>
  <body class="skin-blue">
  	<div class="wrapper">
        <%= render :partial => "layouts/nav_top" %>  
        <!-- Left side column. contains the logo and sidebar -->
        <%= render :partial => "layouts/nav_left" %> 
        
        <%= yield %>
        
        
        <%= render :partial => "layouts/footer" %> 
    </div><!-- ./wrapper -->
    <!-- SCRPTS -->
    <!--<%= javascript_include_tag "plugins/jQuery-2.1.3.min" %>-->
    <%= javascript_include_tag "bootstrap.min" %>
    <%= javascript_include_tag "plugins/jquery.dataTables" %>
    <%= javascript_include_tag "plugins/dataTables.bootstrap" %>
    <%= javascript_include_tag "plugins/jquery.slimscroll.min" %>
    <%= javascript_include_tag "plugins/fastclick.min" %>
    <%= javascript_include_tag "app.min" %>
    <script type="text/javascript">
      $(function () {
        $("#example1").dataTable();
        $('#example2').dataTable({
          "bPaginate": true,
          "bLengthChange": false,
          "bFilter": false,
          "bSort": true,
          "bInfo": true,
          "bAutoWidth": false
        });
      });

    </script>
    <%= javascript_include_tag "http://code.jquery.com/ui/1.10.4/jquery-ui.min.js" %>
  </body>
</html>

app/views/technologies/_form.html.erb
<%= form_for(@technology) do |f| %>
						<% if @technology.errors.any? %>
							<div class="alert alert-danger alert-dismissable">
		                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
		                        <h4><i class="icon fa fa-ban"></i> Alert!</h4>
		                        <% @technology.errors.full_messages.each do |message| %>
		                        * <%= message %> <br>
		                        <% end %>
                        	</div>
	                    <% end %>
						<div class="form-group">
							<%= f.label :name, 'Name' %>
							<%= f.text_field :name, placeholder: "Name", class: "form-control" %>
						</div>
						<div class="form-group">
							<%= f.label :description, 'Description' %>
							<%= f.text_area :description, placeholder: "Description", class: "form-control" %>
						</div>
						<div class="form-group">
							<%= f.label :version, 'Versión' %>
							<%= f.text_field :version, placeholder: "Versión", class: "form-control" %>
						</div>
						<div class="form-group">
							<%= f.label :link, 'Link' %>
							<%= f.text_field :link, placeholder: "Link", class: "form-control" %>
						</div>
						<div class="box-footer">
							<%= f.submit "Save", class: "btn btn-primary" %>
						</div>
					<% end %>

app/views/technologies/edit.html.erb
<!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Edit Technology
          </h1>
          <ol class="breadcrumb">
            <li>
            	<%= link_to technologies_path(@technology) do %>
	              <i class="fa fa-github"></i> Technologies
	            <% end %>
            </li>
            <li class="active">Edit</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">

          <div class="row">
            <!-- left column -->
            <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <!--<h3 class="box-title">Quick Example</h3>-->
                </div><!-- /.box-header -->
                <!-- form start -->
                
				<div class="box-body">
					<%= render "form" %>
				</div><!-- /.box-body -->
              </div><!-- /.box -->
            </div>
          </div>   <!-- /.row -->

        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

app/views/technologies/index.html.erb
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Technologies
            <!--<small>advanced tables</small>-->
          </h1>
          <div class="row" style="margin-top:1em">
            <div class="col-xs-4">

            </div>
            <div class="col-xs-4">

            </div>
            <div class="col-xs-4 text-right">
              <a href="technologies/new" class="btn btn-primary"><i class="fa fa-plus-square"></i> Add Technology</a>
            </div>
          </div>
          <ol class="breadcrumb">
            <li class="active">Technologies</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">
              <div class="box">
                <div class="box-header">
                  <!--<h3 class="box-title">Data Table With Full Features</h3>-->
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>Name</th>
                        <th>Link</th>
                        <th>Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @technologies.each do |technology| %>
                      <tr>
                      	<td><%= technology.name %></td>
                      	<td><%= technology.link %></td>
                        <td>
                          <%= link_to edit_technology_path(technology.id) do %> 
                            <i class="fa fa-edit"></i>
                          <% end %> &nbsp;&nbsp;&nbsp; - &nbsp;&nbsp;&nbsp;
                          <%= link_to technology, :id => 'delete_record', method: :delete do %> 
                            <i class="fa fa-trash"></i>
                          <% end %>
                        </td>
                      </tr>
                  	  <%end%>
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>Name</th>
                        <th>Link</th>
                        <th>Actions</th>
                      </tr>
                    </tfoot>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

app/views/technologies/new.html.erb
<!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Add Technology
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-file-text"></i> khkhkh</a></li>
            <li class="active">Add</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">

          <div class="row">
            <!-- left column -->
            <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <!--<h3 class="box-title">Quick Example</h3>-->
                </div><!-- /.box-header -->
                <!-- form start -->
                
				<div class="box-body">

					<!-- <div class="alert alert-danger alert-dismissable">
					    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
					    <h4><i class="icon fa fa-ban"></i> Alert!</h4>
					    sdsdsds
						</div>
					<div class="form-group">
					  <label>* xcxc</label>
					  <input type="text" class="form-control" name="id_user" id="id_user">
					</div>-->
					<%= form_for(@technology) do |f| %>
						<% if @technology.errors.any? %>
							<div class="alert alert-danger alert-dismissable">
		                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
		                        <h4><i class="icon fa fa-ban"></i> Alert!</h4>
		                        <% @technology.errors.full_messages.each do |message| %>
		                        * <%= message %> <br>
		                        <% end %>
                        	</div>
	                    <% end %>
						
						<div class="form-group">
							<%= f.label :name, 'Name' %>
							<%= f.text_field :name, placeholder: "Name", class: "form-control" %>
						</div>
						<div class="form-group">
							<%= f.label :description, 'Description' %>
							<%= f.text_area :description, placeholder: "Description", class: "form-control" %>
						</div>
						<div class="form-group">
							<%= f.label :version, 'Versión' %>
							<%= f.text_field :version, placeholder: "Versión", class: "form-control" %>
						</div>
						<div class="form-group">
							<%= f.label :link, 'Link' %>
							<%= f.text_field :link, placeholder: "Link", class: "form-control" %>
						</div>
						<div class="box-footer">
							<%= f.submit "Save", class: "btn btn-primary" %>
						</div>
					<% end %>
				</div><!-- /.box-body -->
              </div><!-- /.box -->
            </div>
          </div>   <!-- /.row -->

        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

app/views/technologies/show.html.erb
<!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Detail Technology
          </h1>
          <ol class="breadcrumb">
            <li>
            	<%= link_to technologies_path(@technology) do %>
	              <i class="fa fa-github"></i> Technologies
	            <% end %>
            </li>
            <li class="active">Add</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">

          <div class="row">
            <!-- left column -->
            <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <!--<h3 class="box-title">Quick Example</h3>-->
                </div><!-- /.box-header -->
                <!-- form start -->
                
				<div class="box-body">
					<h1><%= @technology.name %></h1>
					<%= @technology.description %>
				</div><!-- /.box-body -->
              </div><!-- /.box -->
            </div>
          </div>   <!-- /.row -->

        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

app/views/welcome/index.html.erb
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            kjkjskjs
            <!--<small>advanced tables</small>-->
          </h1>
          <div class="row" style="margin-top:1em">
            <div class="col-xs-4">

            </div>
            <div class="col-xs-4">

            </div>
            <div class="col-xs-4 text-right">
              <a href="content_add.php" class="btn btn-primary"><i class="fa fa-plus-square"></i> sddsd</a>
            </div>
          </div>
          <ol class="breadcrumb">
            <li class="active">sdsds</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">
              <div class="box">
                <div class="box-header">
                  
                  sdsdsdsd
                  <!--<h3 class="box-title">Data Table With Full Features</h3>-->
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>sdsd</th>
                        <th>sdsd</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                    <tr>
                      <td>1</td>
                      <td>1</td>
                      <td>2</td>
                    </tr>
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>sdsd</th>
                        <th>sdsd</th>
                        <th></th>
                      </tr>
                    </tfoot>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->